name: Clau
favicon: null
layout_spectrum: 1
typography_spectrum: 0.1788391985464841
title: Head of Media and Intelligence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.9560282491147518
  lightness: 0.4795120076742023
  saturation: 0.30612909654155374
  rhythmicContrast: 1
purpose: []
